### ISSUE TITLE
0003 - 05/04/2023

### ISSUE THREAD

**Issue by lucian-bonifacio** [lucian-bonifacio/html-css#2]
Foi uma aula totalmente prática onde apenas foi desenvido um site com o objetivo de deixá-lo melhor apresentável com os seletores CSS demonstrados abaixo.

Não houve qualquer explicação sobre os seletores e, ainda, houveram afirmações de que cada seletor deste seria melhor explicado em aulas futuras, portanto, não tive qualquer cuidado em enfatizar a teoria de qualquer um.

_OBS:_  Neste caso buscou uma paleta de cores pronta no site da [Adobe Color](https://color.adobe.com/pt/create/color-wheel). Não repeti o processo de pegar uma paleta pronta pois não é meu interesse profissional, uma vez que deixarei o designe sempre para os profissionais desta área. Eu tenho mesmo que aprender é **COPIAR.**

**Código da aula de hoje:** 
```css
@charset "UTF-8";

* {
    font-family: Arial, Helvetica, sans-serif;
}

body {
    background-image: linear-gradient(to right, #f1d8c9, #f2c3a7);
}

main {
    background-color: white;
    border-radius: 10px;
    box-shadow: 5px 5px 15px rgba(136, 103, 88, 0.616);
    width: 600px;
    padding: 10px;
    margin: auto;
}

h1 {
    color: #f39209;
    text-align: center;
    text-shadow: 1px 1px 2px #f39209;
}

h2 {
    color: #125189;
}

p {
    text-align: justify;
}
```
