### ISSUE TITLE
0005 - 11/04/2023

### ISSUE THREAD

**Issue by lucian-bonifacio** [lucian-bonifacio/html-css#3]
# Família de fonte
## font-family
A discussão inteira é como definir as fontes para o seu site considerando suas famílias, pois é possível que, se escolher somente uma fonte, algum dispositivo que acesse o site não possua aquela fonte que você definiu, portanto, ao escolher uma família, esse risco vai para 0 (zero).

Uma forma de pesquisar a família de fontes é através da expressão **CSS web Safe Fonts** no google. 

Exemplos de código:
```css
 <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }

        h1, h2 {
            font-family: 'Times New Roman', Times, serif;
        }
</style>
```

## font-size
Neste caso estamos falando do tamanho da fonte e teve uma aula específica somente para este assunto.
**Medidas abslutas**
cm, mm, in (polegadas), px, pt. pc (paica)

**Medidas relativas**
em, ex, rem, vw, vh, %

16px =  1em (geralmente)

**OBS:** Oficialmente é recomendado a utilização das medidas `px` e `em`.

Exemplo de código:
```css
<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 1em;
        }
    </style>
```
## font-weight
Representa o "peso" da fonte. Basicamente são quatro características: `lighter normal bold bolder`.

**OBS¹:** Não são todas as fontes que aceitam todos esses valores.
**OBS²:** Posso utilizá-los atravez de um `shorthand`, ou uma "mãozinha".

`font: italic bolder 3em 'work sans', sas-serif;`

**OBS³:** Atenção a ordem de preenchimento: font-style -> font-weight -> font-size -> font-family. 

## font-style
Não aula não se falou muito dessa propriedade, mas foi a partir de dela que foi definido o _italico_, então, com o tempo conhecerei todos os valores possível dentro desta propriedade.

## Conclusão
 Me parece que não se utiliza aquelas TAGs no HTMl para fazer as definições de negrito ou itálico, por exemplo, apenas essas propriedades CSS supracitados.
