### ISSUE TITLE
0006 - 13/04/2023

### ISSUE THREAD

**Issue by lucian-bonifacio** [lucian-bonifacio/html-css#4]
# Alinhamento de Textos
Propriedade **text-align**
A propriedade `text-align`, no CSS, trabalha com o alinhamento dos textos. Possui os valores `center`, `left`, `right` e `justify`.

Propriedade **text-indent**
Esta propriedade trabalha com a indentação da primeira linha do parágrado. Semelhante quando escrevemos uma redação.

**Código:**
```CSS
  <style>
      body {
          font: normal 16px  Arial, Verdana, serif;
      }

      h1 {
          text-align: center;
      }

      h2 {
          text-align: right;
      }

      p {
          text-align: justify;
          text-indent: 30px;
      }
  </style>

```
